[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "api"
version = "0.1.0"
description = "API package demonstrating package dependencies"
requires-python = ">=3.11"
dependencies = [
    "core",
    "utils",
]

[tool.uv.sources]
core = { workspace = true }
utils = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/api"]

